proxy:
  listen:
    address: '0.0.0.0'
    port: 8002
  services:
    - name: service-one
      domain: service-one.my-company.com
      lbPolicy: 'RANDOM'
      timeout: '10s'
      retries: 3
      healthCheckTimeout: '10s'
      hosts:
        - address: '0.0.0.0'
          port: 1010
        - address: '0.0.0.0'
          port: 1001
    - name: service-two
      domain: service-two.my-company.com
      lbPolicy: 'RANDOM'
      timeout: '10s'
      retries: 3
      hosts:
        - address: '0.0.0.0'
          port: 1011
        - address: '0.0.0.0'
          port: 1002
