proxy:
  listen:
    address: '0.0.0.0'
    port: 8002
  services:
    - name: service-one
      domain: service-one.my-company.com
      lbPolicy: 'RANDOM'
      timeout: '10s'
      retries: 3
      healthCheckTimeout: '100s'
      hosts:
        - address: '0.0.0.0'
          port: 8081
        - address: '0.0.0.0'
          port: 8082
    - name: service-two
      domain: service-two.my-company.com
      lbPolicy: 'RANDOM'
      timeout: '100s'
      retries: 3
      hosts:
        - address: '0.0.0.0'
          port: 8083
        - address: '0.0.0.0'
          port: 8084
