version: '3.9'
services:
  reverseproxy:
    build: .
    ports: 
      - 8080:8080
    volumes: 
      - "./config.yaml:/config.yaml"
        
  httpbin1:
    image: kennethreitz/httpbin
    ports: 
      - 8081:80    

  httpbin2:
    image: kennethreitz/httpbin
    ports: 
      - 8082:80
  httpbin3:
    image: kennethreitz/httpbin
    ports: 
      - 8083:80
  httpbin4:
    image: kennethreitz/httpbin
    ports: 
      - 8084:80